### ISSUE TITLE
企业微信中间件授权问题

### ISSUE THREAD

**Issue by chenmingwei** [qiqizjl/think-wechat#11]
middleware('\Naixiaoxin\ThinkWechat\Middleware\OauthMiddleware::class:work:test')
在开发企业微信应用时调用中间件auth授权出错。是传参错了吗

**Comment by qiqizjl** [comment]
授权中间件 目前只支持公众号 未支持企业微信~ 目前只能自己根据EasyWechat实现

**Comment by chenmingwei** [comment]
谢谢，老大
