### ISSUE TITLE
component_verify_ticket问题

### ISSUE THREAD

**Issue by xylong** [qiqizjl/think-wechat#13]
`$openPlatform = Facade::openPlatform();
$openPlatform->getPreAuthorizationUrl('https://easywechat.com/callback');`
的时候报component_verify_ticket错误“Credential "component_verify_ticket" does not exist in cache.”

**Comment by qiqizjl** [comment]
开放平台接入 需要先让微信那边callback一个ticket之后才可以调用。
看下访问日志，看下微信有调用callback的接口

**Comment by kekesita** [comment]
> 开放平台接入需要先让微信那边回电一个票之后才可以调用。
> 看下访问日志，看下微信有调用callback的接口

我也出现了这个问题 具体是在哪里定义这个回调

**Comment by qiqizjl** [comment]
> > 开放平台接入需要先让微信那边回电一个票之后才可以调用。
> > 看下访问日志，看下微信有调用callback的接口
> 
> 我也出现了这个问题 具体是在哪里定义这个回调

微信开放平台里
![image](https://user-images.githubusercontent.com/7540584/58223775-a1156b00-7d4d-11e9-864b-c6f880017481.png)

**Comment by kekesita** [comment]
> > > 开放平台接入需要先让微信那边回电一个票之后才可以调用。
> > > 看下访问日志，看下微信有调用回调函数的接口
> > 
> > 
> > 我也出现了这个问题具体是在哪里定义这个回调
> 
> 微信开放平台里
> ![图片](https://user-images.githubusercontent.com/7540584/58223775-a1156b00-7d4d-11e9-864b-c6f880017481.png)

不好意思  从哪里进去的真的没找到

**Comment by qiqizjl** [comment]
@twelveandone 微信开放平台->第三方应用→修改平台→下一步到填写开发资料

**Comment by kekesita** [comment]
好的  感谢
