### ISSUE TITLE
升级overtrue/wechat到最新后出错

### ISSUE THREAD

**Issue by xzusoft** [qiqizjl/think-wechat#16]
Interface 'Psr\SimpleCache\CacheInterface' not found

**Comment by xzusoft** [comment]
最新的overtrue/wechat，删除了对psr/simple-cache的依赖

**Comment by xzusoft** [comment]
说错了删除的是psr/simple-cache

**Comment by qiqizjl** [comment]
我这边跟进看下

**Comment by qiqizjl** [comment]
看了下 这个东西确实有点迷~ 我这边先看下~ 你可以先将配置中的
![image](https://user-images.githubusercontent.com/7540584/58763064-1a506180-8589-11e9-840c-3aff4a8e6a44.png)cache关掉

**Comment by qiqizjl** [comment]
是``symfony/cache``在4.3.0中干掉了psr/simple-cache 
你可以直接引入
~~~
 composer require psr/simple-cache
~~~
或者更新新版本
后续再来看如何干掉这个包

**Comment by xzusoft** [comment]
后面我自己安安装psr/simple-cache，希望官方出个方案把这个干掉

**Comment by qiqizjl** [comment]
EasyWechat在官方包中加入了``psr/simple-cache``
overtrue/wechat#1553
