### ISSUE TITLE
AppID 不合法

### ISSUE THREAD

**Issue by mwz747512353** [qiqizjl/think-wechat#19]
使用jssdk 控制台报错AppID 不合法，确定合法其他调用都正常
![image](https://user-images.githubusercontent.com/19990937/69033024-f5598900-0a18-11ea-9a35-9ce4323a99e8.png)
![image](https://user-images.githubusercontent.com/19990937/69033170-51bca880-0a19-11ea-90fe-5064e808ac55.png)

**Comment by mwz747512353** [comment]
@qiqizjl

**Comment by mwz747512353** [comment]
@psr4 @fossabot @qiqizjl

**Comment by qiqizjl** [comment]
检查下这个appid是否有付费？

**Comment by qiqizjl** [comment]
是个对象 不是字符串


https://www.easywechat.com/docs/4.1/basic-services/jssdk

**Comment by mwz747512353** [comment]
> 是个对象 不是字符串
> 
> https://www.easywechat.com/docs/4.1/basic-services/jssdk

![image](https://user-images.githubusercontent.com/19990937/69038118-2b503a80-0a24-11ea-99e5-5e547b91950c.png)

**Comment by qiqizjl** [comment]
> > 是个对象 不是字符串
> > https://www.easywechat.com/docs/4.1/basic-services/jssdk
> 
> ![image](https://user-images.githubusercontent.com/19990937/69038118-2b503a80-0a24-11ea-99e5-5e547b91950c.png)

截图下模板的代码 截图全

**Comment by mwz747512353** [comment]
> > > 是个对象 不是字符串
> > > https://www.easywechat.com/docs/4.1/basic-services/jssdk
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/19990937/69038118-2b503a80-0a24-11ea-99e5-5e547b91950c.png)
> 
> 截图下模板的代码 截图全

![image](https://user-images.githubusercontent.com/19990937/69038260-6b172200-0a24-11ea-88ba-0e7c91aa1091.png)

**Comment by mwz747512353** [comment]
> > > > 是个对象 不是字符串
> > > > https://www.easywechat.com/docs/4.1/basic-services/jssdk
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/19990937/69038118-2b503a80-0a24-11ea-99e5-5e547b91950c.png)
> > 
> > 
> > 截图下模板的代码 截图全
> 
> ![image](https://user-images.githubusercontent.com/19990937/69038260-6b172200-0a24-11ea-88ba-0e7c91aa1091.png)

![image](https://user-images.githubusercontent.com/19990937/69038304-81bd7900-0a24-11ea-9d65-5e691ba4a277.png)
![image](https://user-images.githubusercontent.com/19990937/69038335-913cc200-0a24-11ea-8b11-2db69fee79d7.png)

**Comment by qiqizjl** [comment]
![image](https://user-images.githubusercontent.com/7540584/69038327-8bdf7780-0a24-11ea-94b6-f60a868e970d.png)
wx.config(jssdk)
不是wx.config("$jssdk")
不需要引号包裹

**Comment by mwz747512353** [comment]
> ![image](https://user-images.githubusercontent.com/7540584/69038327-8bdf7780-0a24-11ea-94b6-f60a868e970d.png)
> wx.config(jssdk)
> 不是wx.config("$jssdk")
> 不需要引号包裹

OK了，现在是这个问题
![image](https://user-images.githubusercontent.com/19990937/69038465-cfd27c80-0a24-11ea-882c-9b3261930494.png)

**Comment by qiqizjl** [comment]
麻烦看下微信文档吧
https://developers.weixin.qq.com/doc/offiaccount/OA_Web_Apps/JS-SDK.html

**Comment by mwz747512353** [comment]
> 麻烦看下微信文档吧
> https://developers.weixin.qq.com/doc/offiaccount/OA_Web_Apps/JS-SDK.html

解决了，域名url不能带http等协议

**Comment by mwz747512353** [comment]
> 麻烦看下微信文档吧
> https://developers.weixin.qq.com/doc/offiaccount/OA_Web_Apps/JS-SDK.html

谢谢了

**Comment by mwz747512353** [comment]
> 麻烦看下微信文档吧
> https://developers.weixin.qq.com/doc/offiaccount/OA_Web_Apps/JS-SDK.html

大哥，我还有个问题，现在是所有返回都是ok，分享到朋友，为啥不拉起微信好友列表呢？

**Comment by qiqizjl** [comment]
你需要问微信官方 这个和包没有关系



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Liunk <notifications@github.com&gt;
发送时间: 2019年11月18日 17:32
收件人: qiqizjl/think-wechat <think-wechat@noreply.github.com&gt;
抄送: 耐小心 <qiqizjl@qq.com&gt;, State change <state_change@noreply.github.com&gt;
主题: 回复：[qiqizjl/think-wechat] AppID 不合法 (#19)




麻烦看下微信文档吧
https://developers.weixin.qq.com/doc/offiaccount/OA_Web_Apps/JS-SDK.html

大哥，我还有个问题，现在是所有返回都是ok，分享到朋友，为啥不拉起微信好友列表呢？

**Comment by mwz747512353** [comment]
好的------------------ 原始邮件 ------------------
发件人: "耐小心"<notifications@github.com>
发送时间: 2019年11月18日(星期一) 下午5:34
收件人: "qiqizjl/think-wechat"<think-wechat@noreply.github.com>;
抄送: "Liunk"<747512353@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [qiqizjl/think-wechat] AppID 不合法 (#19)


你需要问微信官方 这个和包没有关系 
 
 
 
 发自我的iPhone 
 
 
 ------------------ 原始邮&#x4EF6; ------------------ 
 发&#x4EF6;人: Liunk <notifications@github.com&gt; 
 发送时间: 2019年11月18日 17:32 
 收&#x4EF6;人: qiqizjl/think-wechat <think-wechat@noreply.github.com&gt; 
 抄送: 耐小心 <qiqizjl@qq.com&gt;, State change <state_change@noreply.github.com&gt; 
 主题: 回复：[qiqizjl/think-wechat] AppID 不合法 (#19) 
 
 
 
 
 麻烦看下微信文档吧 
 https://developers.weixin.qq.com/doc/offiaccount/OA_Web_Apps/JS-SDK.html 
 
 大哥，我还有个问题，现在是所有返回都是ok，分享到朋友，为啥不拉起微信好友列表呢？ 
 
 — 
 You are receiving this because you modified the open/close state. 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
&mdash;
