### ISSUE TITLE
ThinkPHP V5.1.15下使用出错

### ISSUE THREAD

**Issue by xzusoft** [qiqizjl/think-wechat#2]
[0] ThrowableError in wechat.php line 31
Fatal error: Call to undefined function storage_path()；

/*
         * 日志配置
         *
         * level: 日志级别，可选为：
         *                 debug/info/notice/warning/error/critical/alert/emergency
         * file：日志文件位置(绝对路径!!!)，要求可写权限
         */
        'log'           => [
            'level' => env('WECHAT_LOG_LEVEL', 'debug'),
            'file'  => env('WECHAT_LOG_FILE', storage_path('logs/wechat.log')),
        ],

**Comment by qiqizjl** [comment]
是的。。我也发现了~ 
你尝试把
~~~php
'file' => env('WECHAT_LOG_FILE', storage_path('logs/wechat.log')),
~~~
改成
~~~php
        'file' => env('WECHAT_LOG_FILE', app()->getRuntimePath()."logs/wechat.log"),
~~~

**Comment by qiqizjl** [comment]
这边先关闭issue啦~ 有问题可以继续追问哦，或者新开issue
