### ISSUE TITLE
从overtrue/wechat滚过来提issue啦

### ISSUE THREAD

**Issue by orchie** [qiqizjl/think-wechat#4]
如题 原issue   https://github.com/overtrue/wechat/issues/1260
BUG一个  配置文件 wechat.php 里的defaults 应该 改成 default

接口返回数据问题:
```
        //三种 返回方式
        //wechat文档写法
        //输出 HTTP/1.0 200 OK Cache-Control: no-cache, private Date: Sun, 17 Jun 2018 12:06:08 GMT success
        return $server->serve();

        //安装了 https://github.com/qiqizjl/think-wechat
        //根据说明 尝试的方法
        //输出了 success 后 又尝试输出一个 boolean 被tp类型检测报错
        $server->serve()->send();

        //由上述方法想到的临时解决方法 立即结束脚本
        //可以只输出 success
        $server->serve()->send();die;
```
send后die只是临时解决方法

easywechat在tp5.1框架下使用symfony无效问题:
这个能找到原因最好拉 不过找不到原因使用tp缓存也是OK的 :smile:

**Comment by qiqizjl** [comment]
哈哈哈 目前我这里是
1:返回
  你可以尝试不return
~~~php
        $app->server->serve()->send();
~~~
这样用的 看起来是OK的

2:配置文件
 确实我粗心啦~ 我这里修复下

3: symfony缓存
 你用的是默认的symfony缓存么~ 

我这边刚刚测试了下，看起来没有问题哦。文件是可以写到/tmp/symfony-cache下的
