### ISSUE TITLE
在V5.1.18+下面log日志无法输出

### ISSUE THREAD

**Issue by 51xvf** [qiqizjl/think-wechat#5]
在V5.1.18+下面log日志无法输出

**Comment by qiqizjl** [comment]
日志目录下也没有么？

**Comment by 51xvf** [comment]
非常感谢作者火速的回答，再次表示感谢！
![image](https://user-images.githubusercontent.com/10204438/42498329-78cf45a0-845e-11e8-9fae-3824c6a99229.png)
![image](https://user-images.githubusercontent.com/10204438/42498352-8627abf2-845e-11e8-8226-9674d4ea35b2.png)
权限已经给了777，还是为空，麻烦看看，不胜感激！

**Comment by 51xvf** [comment]
日志保存默认设置：
return [
    // 日志记录方式，内置 file socket 支持扩展
    'type'        => 'File',
    // 日志保存目录
    'path'        => '',
    // 日志记录级别
    'level'       => [],
    // 单文件日志写入
    'single'      => false,
    // 独立日志级别
    'apart_level' => [],
    // 最大日志文件数量
    'max_files'   => 0,
    // 是否关闭日志写入
    'close'       => false,
];

我的缓存设置：

return [
    // 缓存配置为复合类型
    'type'  =>  'complex',
    'default'	=>	[
        'type'	=>	'file',
        // 全局缓存有效期（0为永久有效）
        'expire'=>  0,
        // 缓存前缀
        'prefix'=>  'think_cache',
        // 缓存目录
        'path'  =>  '../runtime/cache/',
    ],
    'memcache'	=>	[
        'type'	=>	'memcache', //memcached memcache
        'host'	=>	'127.0.0.1',
        // 全局缓存有效期（0为永久有效）
        'expire'=>  0,
        // 缓存前缀
        'prefix'=>  'think_memcache',
    ],
    // 添加更多的缓存类型设置

    'redis'	=>	[
        'type'	=>	'redis',
        'host'	=>	'127.0.0.1',
        // 全局缓存有效期（0为永久有效）
        'expire'=>  0,
        // 缓存前缀
        'prefix'=>  'think_redis',
    ],
    // 添加更多的缓存类型设置

];

**Comment by qiqizjl** [comment]
无法输出日志 是无法输出wechat的日志还是thinkphp的日志呢

**Comment by 51xvf** [comment]
您好，是无法输出wechat的调试日志，thinkphp的可以输出日志呢

**Comment by 51xvf** [comment]
![image](https://user-images.githubusercontent.com/10204438/42498761-a810eaac-845f-11e8-8598-b8aea7fd127e.png)

**Comment by qiqizjl** [comment]
好的 我这边尝试复现下

**Comment by 51xvf** [comment]
好的，非常感谢

**Comment by qiqizjl** [comment]
ehh 看起来是默认配置文件的问题  thinkphp的log在runtime/log下 我写成了logs。 您尝试将配置文件中的logs改成log，或者新建logs文件夹呢~ 我这里测试是OK的呢

**Comment by 51xvf** [comment]
怪了，我就是新建了logs文件并赋予权限，但是还是获不到调试信息

**Comment by qiqizjl** [comment]
你尝试把目录改下看看呢。。 我这里在log目录下是正常的

**Comment by 51xvf** [comment]
好的，我试试

**Comment by 51xvf** [comment]
好怪啊，还是输出不了

**Comment by 51xvf** [comment]
用easywechat，原生php可以获取到

**Comment by qiqizjl** [comment]
配置文件中的defaults 改成default呢 应该是写配置文件的时候不小心。。写错了。。

**Comment by 51xvf** [comment]
哈哈，还真是的，已经好了，也怪我没有看上面哪位仁兄提的问题，不仔细！！再次感谢
