### ISSUE TITLE
单调

### ISSUE THREAD

**Issue by ghost** [qiqizjl/think-wechat#8]
可以不可以考虑多地方使用下呢?

**Comment by qiqizjl** [comment]
您指的是什么呢？

**Comment by ghost** [comment]
在其他地方也可以用, 不仅仅是在thinkphp中

**Comment by qiqizjl** [comment]
https://github.com/overtrue/wechat 
这个包是基于easywechat封装的，如果想在非tp下使用 可直接用easywechat
